# -*- coding: utf-8 -*-
"""talentprofile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_ZwKaJb04XLexe6ZWlDiajwaIbaoFE2
"""

!pip install -q kaggle

import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_b6038a88848c3adccdb821cb0f3383fd"

!kaggle datasets download -d arshkon/linkedin-job-postings

!unzip linkedin-job-postings.zip

import os

files = sorted(os.listdir("/content"))
print(files)

import pandas as pd

postings = pd.read_csv("/content/postings.csv", engine='python', on_bad_lines='skip')
companies = pd.read_csv("/content/companies/companies.csv")
job_skills = pd.read_csv("/content/jobs/job_skills.csv")
job_industries = pd.read_csv("/content/jobs/job_industries.csv")
company_industries = pd.read_csv("/content/companies/company_industries.csv")
company_specialities = pd.read_csv("/content/companies/company_specialities.csv")
employee_counts = pd.read_csv("/content/companies/employee_counts.csv")
industries = pd.read_csv("/content/mappings/industries.csv")
benefits = pd.read_csv("/content/jobs/benefits.csv")
salaries = pd.read_csv("/content/jobs/salaries.csv")
skills = pd.read_csv("/content/mappings/skills.csv")

print("✅ All datasets loaded successfully!")

datasets = {
    "postings": postings,
    "companies": companies,
    "job_skills": job_skills,
    "job_industries": job_industries,
    "company_industries": company_industries,
    "company_specialities": company_specialities,
    "employee_counts": employee_counts,
    "industries": industries,
    "benefits": benefits,
    "salaries": salaries,
    "skills": skills
}

summary = pd.DataFrame({
    "Dataset": datasets.keys(),
    "Rows": [df.shape[0] for df in datasets.values()],
    "Columns": [df.shape[1] for df in datasets.values()]
})

summary

def inspect_dataset(df, name):
    print("=" * 80)
    print(f"DATASET : {name}")
    print("=" * 80)

    print(f"\nShape : {df.shape}")

    print("\nColumn Names")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nFirst Five Rows")
    display(df.head())

inspect_dataset(postings, "Postings")

inspect_dataset(companies, "Companies")

inspect_dataset(job_skills, "Job Skills")

inspect_dataset(job_industries, "Job Industries")

inspect_dataset(industries, "Industries")

inspect_dataset(industries, "Industries")

inspect_dataset(skills, "Skills")

for name, df in {
    "postings": postings,
    "companies": companies,
    "job_skills": job_skills,
    "job_industries": job_industries,
    "industries": industries,
    "skills": skills
}.items():

    print("="*60)
    print(name)
    print("="*60)
    print(df.columns.tolist())

postings.describe(include='all').T

companies.describe(include='all').T

missing = postings.isnull().sum().sort_values(ascending=False)

missing = missing[missing > 0]

missing

print("Postings :", postings.duplicated().sum())

print("Companies :", companies.duplicated().sum())

print("Job Skills :", job_skills.duplicated().sum())

"""## Business Understanding

Goal:

Develop an AI-powered Universal Freelancer Recommendation System.

The dataset contains LinkedIn job postings and related metadata.

The recommendation system will transform job information into searchable freelancer-like profiles.

The final system will recommend the best matching professionals based on natural language requirements using NLP.

Key datasets:

- postings → job information
- companies → company details
- job_skills → required skills
- industries → industry names
"""

postings.columns.tolist()

companies.columns.tolist()

job_skills.columns.tolist()

job_industries.columns.tolist()

industries.columns.tolist()

skills.columns.tolist()

postings.columns.tolist()

postings.info()

missing = (
    postings.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

postings.head().T

postings.columns.tolist()

postings_clean = postings[[
    "job_id",
    "company_id",
    "company_name",
    "title",
    "description",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skills_desc"
]].copy()

postings_clean.head()

postings_clean.isnull().sum().sort_values(ascending=False)

print("Duplicates Before:", postings_clean.duplicated().sum())

postings_clean.drop_duplicates(inplace=True)

print("Duplicates After:", postings_clean.duplicated().sum())

text_columns = [
    "title",
    "description",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skills_desc"
]

for col in text_columns:
    postings_clean[col] = postings_clean[col].fillna("")

companies_clean = companies[[
    "company_id",
    "name",
    "description"
]].copy()

companies_clean.columns = [
    "company_id",
    "company_name_full",
    "company_description"
]

master_df = postings_clean.merge(
    companies_clean,
    on="company_id",
    how="left"
)

master_df.head()

master_df = master_df.merge(
    job_skills,
    on="job_id",
    how="left"
)

master_df = master_df.merge(
    skills,
    on="skill_abr",
    how="left"
)

master_df.head()

master_df = master_df.merge(
    job_industries,
    on="job_id",
    how="left"
)

master_df = master_df.merge(
    industries,
    on="industry_id",
    how="left"
)

master_df.head()

print(master_df.shape)

master_df.head()

master_df.shape

master_df.head()

postings_clean.isnull().sum().sort_values(ascending=False)

skills_grouped = (
    master_df
    .groupby("job_id")["skill_name"]
    .apply(lambda x: ", ".join(sorted(set(x.dropna()))))
    .reset_index()
)

skills_grouped.head()

talent_profiles = (
    master_df
    .drop_duplicates(subset="job_id")
    .copy()
)

talent_profiles.drop(
    columns=["skill_name", "skill_abr"],
    inplace=True
)

talent_profiles = talent_profiles.merge(
    skills_grouped,
    on="job_id",
    how="left"
)

print("Master DF :", master_df.shape)

print("Talent Profiles :", talent_profiles.shape)

talent_profiles.head()

talent_profiles["combined_text"] = (
    talent_profiles["title"].fillna("") + " " +
    talent_profiles["skill_name"].fillna("") + " " +
    talent_profiles["industry_name"].fillna("") + " " +
    talent_profiles["description"].fillna("") + " " +
    talent_profiles["company_description"].fillna("") + " " +
    talent_profiles["formatted_experience_level"].fillna("")
)

talent_profiles.shape

talent_profiles[["job_id", "title", "skill_name"]].head(10)

talent_profiles.isnull().sum().sort_values(ascending=False)

text_columns = [
    "title",
    "company_name",
    "company_name_full",
    "company_description",
    "description",
    "industry_name",
    "location",
    "formatted_work_type",
    "formatted_experience_level",
    "skill_name"
]

for col in text_columns:
    if col in talent_profiles.columns:
        talent_profiles[col] = talent_profiles[col].fillna("")

talent_profiles["combined_text"] = (

    talent_profiles["title"] + " " +

    talent_profiles["skill_name"] + " " +

    talent_profiles["industry_name"] + " " +

    talent_profiles["description"] + " " +

    talent_profiles["company_description"] + " " +

    talent_profiles["formatted_experience_level"] + " " +

    talent_profiles["formatted_work_type"]

)

talent_profiles[[
    "title",
    "skill_name",
    "industry_name",
    "combined_text"
]].head()

import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

stop_words = ENGLISH_STOP_WORDS

def clean_text(text):
    # Convert to string
    text = str(text).lower()

    # Remove HTML
    text = re.sub(r"<.*?>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Keep only letters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Remove stopwords
    words = [
        word for word in text.split()
        if word not in stop_words
    ]

    return " ".join(words)

talent_profiles["clean_text"] = talent_profiles["combined_text"].apply(clean_text)

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2)
)

tfidf_matrix = vectorizer.fit_transform(
    talent_profiles["clean_text"]
)

print(tfidf_matrix.shape)

def recommend_talent(query, top_n=10):

    # Clean query
    query = clean_text(query)

    # Convert query into TF-IDF vector
    query_vector = vectorizer.transform([query])

    # Calculate similarity
    similarity = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    # Top matching indices
    top_indices = similarity.argsort()[-top_n:][::-1]

    # Create result dataframe
    results = talent_profiles.iloc[top_indices].copy()

    results["Similarity Score"] = similarity[top_indices]

    return results[
        [
            "title",
            "company_name",
            "industry_name",
            "skill_name",
            "formatted_experience_level",
            "location",
            "Similarity Score"
        ]
    ]

recommend_talent(
    "Need a motion graphics designer for real estate"
)

recommend_talent(
    "Need a UI UX designer"
)

def display_recommendations(query):

    results = recommend_talent(query)

    print("=" * 80)
    print(f"Query: {query}")
    print("=" * 80)

    for idx, (_, row) in enumerate(results.iterrows(), start=1):

        print(f"\n🏆 Rank {idx}")

        print(f"Title : {row['title']}")

        print(f"Company : {row['company_name']}")

        print(f"Industry : {row['industry_name']}")

        print(f"Skills : {row['skill_name']}")

        print(f"Experience : {row['formatted_experience_level']}")

        print(f"Location : {row['location']}")

        print(f"Similarity : {row['Similarity Score']:.3f}")

display_recommendations(
    "Need someone who creates luxury real estate reels using motion graphics"
)

display_recommendations("Need a Python Data Analyst")

display_recommendations("Need a UI UX Designer")

display_recommendations("Need a Motion Graphics Designer")

display_recommendations("Need a Real Estate Marketing Expert")

display_recommendations("Need a Machine Learning Engineer")

"""# Conclusion

TalentMatch AI successfully recommends relevant talent profiles using NLP.

Achievements:

✔ Cleaned and integrated 11 LinkedIn datasets

✔ Built a Talent Profile knowledge base

✔ Engineered textual features

✔ Applied TF-IDF vectorization

✔ Used Cosine Similarity for recommendation

Current Limitation:

The model relies on keyword similarity.

Future Improvements:

• Sentence Transformers
• FAISS
• Explainable AI
• Hybrid Ranking
"""

import joblib

# Save the TF-IDF vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

# Save the Talent Profiles
joblib.dump(talent_profiles, "talent_profiles.pkl")

# Save the TF-IDF matrix
joblib.dump(tfidf_matrix, "tfidf_matrix.pkl")

print("All files saved successfully!")